// Auto-generated entity names from the scene


/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  Arrow_Height = "Arrow_Height",
  Arrow_Turn = "Arrow_Turn",
  Ball = "Ball",
  Barriers_glb = "Barriers.glb",
  Black = "Black",
  Blue = "Blue",
  Chairs_glb = "Chairs.glb",
  Chairs_glb_2 = "Chairs.glb_2",
  Environment = "Environment",
  Golf_Bags_glb = "Golf Bags.glb",
  Golf_Club_Podiums_glb = "Golf Club Podiums.glb",
  Green = "Green",
  Hook_Railing_glb = "Hook Railing.glb",
  Logo_glb = "Logo.glb",
  Logos_glb = "Logos.glb",
  Main_Building_glb = "Main Building.glb",
  Mountains_glb = "Mountains.glb",
  Orange = "Orange",
  Planters_glb = "Planters.glb",
  Plants_glb = "Plants.glb",
  Podium_Frame_glb = "Podium Frame.glb",
  Podium_Lights_glb = "Podium Lights.glb",
  Podiums_glb = "Podiums.glb",
  Red1 = "Red1",
  Red2 = "Red2",
  Red3 = "Red3",
  Red4 = "Red4",
  Screens_glb = "Screens.glb",
  Shelves_glb = "Shelves.glb",
  Shop_Counter_glb = "Shop Counter.glb",
  Shop_Light_glb = "Shop Light.glb",
  Stairs_glb = "Stairs.glb",
  Steps_glb = "Steps.glb",
  Tee_Off_Panels_glb = "Tee Off Panels.glb",
  Training_Area_Frame_glb = "Training Area Frame.glb",
  Trims_glb = "Trims.glb",
  Wall_of_Honor_Podium_glb = "Wall of Honor Podium.glb",
  White = "White",
  Yellow1 = "Yellow1",
  Yellow2 = "Yellow2",
  backdrop_glb = "backdrop.glb",
  bunker_green_glb = "bunker_green.glb",
  cliffs_glb = "cliffs.glb",
  clothing_glb = "clothing.glb",
  cube_glb = "cube.glb",
  display_balls_glb = "display_balls.glb",
  grass_glb = "grass.glb",
  hats_glb = "hats.glb",
  holes_glb = "holes.glb",
  shop_banner_glb = "shop_banner.glb",
  shop_banner_2_glb = "shop_banner_2.glb",
  stacked_shirts_glb = "stacked_shirts.glb",
  trees_glb = "trees.glb",
} 
